package com.demo.app;// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsNot.not;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@ExtendWith(SeleniumJupiter.class)
public class AirQualityLastTest {
  private FirefoxDriver driver;

  public AirQualityLastTest(FirefoxDriver driver){
    this.driver=driver;
  }

  @Test
  public void airQualityLastTest(FirefoxDriver driver) {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(701, 705));
    driver.findElement(By.id("services")).click();
    {
      WebElement dropdown = driver.findElement(By.id("services"));
      dropdown.findElement(By.xpath("//option[. = 'Previous']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    driver.findElement(By.name("local")).click();
    driver.findElement(By.name("local")).sendKeys("Aveiro");
    driver.findElement(By.cssSelector(".btn")).click();
    long unixTime = Instant.now().getEpochSecond()*1000;
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyy");
    String date = dateFormat.format(unixTime);
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(5) > td:nth-child(1)")).getText(), is(date));
  }
}
